### ISSUE TITLE
Add string key aliases for output field harmonics (`fieldN_key` N > 1)

### ISSUE THREAD

**Issue by ken-lauer** [slaclab/lume-genesis#35]
1. This `power` key catch-all is back-compat that should go away from Chris's original code:

https://github.com/ken-lauer/lume-genesis/blob/a15c20ec1d4c3fe2a4c60496619fe09c8a7cd8c4/genesis/version4/output.py#L1618-L1622

2. Then we need to add string aliases for field harmonics beyond the first one, which are present in `field_harmonics[N].attr`
3. Chris indicated that `field3_energy` (for example) would be a good pattern here

**Comment by ChristopherMayes** [comment]
There's no way to make sense of averaging the field power for creating the stats data, so I had 'corrected' the request for plotting power as the peak power. Now we should probably just disallow that, and instead have the user request `peak_power` from the stats. We could throw in a helpful message in the error.
